management:
  endpoint:
    gateway:
      enabled: false
    refresh:
      enabled: false
    pause:
      enabled: false
    restart:
      enabled: false
    resume:
      enabled: false
    service-registry:
      enabled: false
    features:
      enabled: false
    env:
      post:
        enabled: false
  health:
    refresh:
      enabled: false
spring:
  cloud:
    service-registry:
      auto-registration:
        register-management: false
#    gateway:
#      routes:
#        - id: api-file
#          uri: forward:/doc/**
#          predicates:
#            - Path=/doc/**

      metrics:
        enabled: false
  webflux:
    static-path-pattern: /doc/**
  resources:
    static-locations: /Users/evans/GitHub/simple-api-doc/api-html/